version: "3.8"
services:
    cats-cradle:
        build:
            context: .
            dockerfile: Dockerfile
            target: test
        container_name: cats-cradle
        tty: true
        stdin_open: true
