version: '3.8'
services:
    cdk-monorepo:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        container_name: cdk-monorepo
        tty: true
        stdin_open: true
        volumes:
            - .:/usr/src/app
            - .devcontainer/.aws:/home/node/.aws
            - github-ssh-key:/home/node/github-ssh-key
            # - .devcontainer/.ssh/config:/home/node/.ssh/config

volumes:
   github-ssh-key:
