version: "3.8"
services:
    keepers-cradle:
        build:
            context: .
            dockerfile: Dockerfile
            target: test
        container_name: keepers-cradle
        tty: true
        stdin_open: true
