version: '3.8'
services:
    monorepo:
        container_name: monorepo
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        volumes:
            - .:/usr/src/app