AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 124653296725

Organization:

  MasterAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: root
      AccountId: '124653296725'
      RootEmail: hooplessws@gmail.com

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      ServiceControlPolicies:
        - !Ref DenyChangeOfOrgRoleSCP
        - !Ref RestrictUnusedRegionsSCP

  ToolsAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: tools
      AccountId: '760440398296'
      RootEmail: matthew.heroux+tools@gmail.com
      Alias: tools-1
      Tags:
        subdomain: tools

  SandboxAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: sandbox
      AccountId: '298217020330'
      RootEmail: matthew.heroux+sandbox@gmail.com
      # Alias: sandbox-1
      Tags:
        subdomain: sandbox

  RestrictUnusedRegionsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: RestrictUnusedRegions
      Description: Restrict Unused regions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnsupportedRegions
            Effect: Deny
            NotAction:
              - 'cloudfront:*'
              - 'iam:*'
              - 'route53:*'
              - 'support:*'
              - 'budgets:*'
            Resource: '*'
            Condition:
              StringNotEquals:
                'aws:RequestedRegion':
                  - us-east-2
                  - us-east-1

  DenyChangeOfOrgRoleSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: DenyChangeOfOrgRole
      Description: Deny changing the IAM role used for organization access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyChangeOfOrgRole
            Effect: Deny
            Action:
              - 'iam:Attach*'
              - 'iam:Create*'
              - 'iam:Delete*'
              - 'iam:Detach*'
              - 'iam:PutRole*'
              - 'iam:Update*'
            Resource:
              - 'arn:aws:iam::*:role/OrganizationAccountAccessRole'

  PasswordPolicy:
    Type: OC::ORG::PasswordPolicy
    Properties:
      MinimumPasswordLength: 12
      RequireLowercaseCharacters: true
      RequireNumbers: true
      RequireSymbols: true
      RequireUppercaseCharacters: true
      AllowUsersToChangePassword: true
