name: Lint

on:
    workflow_call:

jobs:
  lint:
    name: rush lint
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'

      - name: Cache rush
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: common/temp
          key: ${{ runner.os }}-build-branch-${{ hashFiles('common/config/rush/repo-state.json') }}
          restore-keys: |
            ${{ runner.os }}-build-pr-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Rush install
        # if: steps.cache.outputs.cache-hit != 'true'
        run: node common/scripts/install-run-rush.js install

      - name: lint
        run: node common/scripts/install-run-rush.js lint:ci
