name: Deploy

on:
  workflow_call:
    secrets:
      AWS_DEPLOY_ACCESS_KEY_ID:
        required: true
      AWS_DEPLOY_SECRET_ACCESS_KEY:
        required: true
      AWS_DEPLOY_REGION:
        required: true

jobs:
  rush-deploy:
    name: rush deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'

      - name: cache rush
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: common/temp
          key: ${{ runner.os }}-build-branch-${{ hashFiles('common/config/rush/repo-state.json') }}
          restore-keys: |
            ${{ runner.os }}-build-pr-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup git
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com

      - name: rush install
        run: node common/scripts/install-run-rush.js install

      - name: rush build
        run: node common/scripts/install-run-rush.js build

      - name: install pnpm needed for cdk NodeJsFunction esbuild
        run: npm install --global pnpm@7.26.3

      - name: install rush to avoid header issue with list
        run: npm install --global @microsoft/rush@5.88.0

      # build deployment package
      # https://rushjs.io/pages/maintainer/deploying/
      - name: rush deploy
        run: |
          BASE_DIR=${GITHUB_WORKSPACE} \
          mkdir -p $BASE_DIR/.deploy \
          RUSH_LIST_JSON=$(rush list --only tag:deploy-app --json) \
          RUSH_LIST_ARRAY=$(RUSH_LIST_JSON | jq '.[]') \
          PROJECTS=${RUSH_LIST_JSON[projects]} \
          for row in $(echo "${PROJECTS}" | jq -r '.[] | @base64'); do \
            _jq() { \
              echo "${row}" | base64 --decode | jq -r "${1}" \
            } \
            \
            name=$(_jq '.name') \
            appShortName=${name//@cats-cradle\//deploy_} \
            node $BASE_DIR/common/scripts/install-run-rush.js deploy --overwrite --project $name --create-archive $BASE_DIR/.deploy/$appShortName.zip \
          done
      # authenticate
      # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_DEPLOY_REGION }}
      #     role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      #     role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
      #     role-duration-seconds: 1200
      #     role-session-name: MySessionName

      # ship deployments for each project for use in aws code pipelines