name: Publish

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  rush-publish:
    name: rush publish
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'

      - name: cache rush
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: common/temp
          key: ${{ runner.os }}-build-branch-${{ hashFiles('common/config/rush/repo-state.json') }}
          restore-keys: |
            ${{ runner.os }}-build-pr-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup git
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com

      - name: rush install
        run: node common/scripts/install-run-rush.js install

      - name: rush build
        run: node common/scripts/install-run-rush.js build

      - name: bump version
        run: node common/scripts/install-run-rush.js version --bump

      # https://rushjs.io/pages/maintainer/publishing/
      # uses shouldPublish in rush.json
      - name: rush publish to npm
        run: node common/scripts/install-run-rush.js publish --apply --publish --include-all --target-branch main --npm-auth-token ${NPM_TOKEN} --add-commit-details --set-access-level public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
