name: Deploy

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_BUCKET:
        required: true
      AWS_REGION:
        required: true

jobs:
  rush-deploy:
    name: rush deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: step-deployment-action
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          description: 'Upload AWS S3'
          environment: AWS CodePipeline

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'

      - name: cache rush
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: common/temp
          key: ${{ runner.os }}-build-branch-${{ hashFiles('common/config/rush/repo-state.json') }}
          restore-keys: |
            ${{ runner.os }}-build-pr-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup git
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com

      - name: rush install
        run: node common/scripts/install-run-rush.js install

      - name: rush build
        run: node common/scripts/install-run-rush.js build

      - name: install pnpm needed for cdk NodeJsFunction esbuild
        run: npm install --global pnpm@7.26.3

      - name: rush deploy
        run: |
            node common/scripts/install-run-rush.js deploy --overwrite --project @cats-cradle/lambda-layers --create-archive lambda-layers.zip
            mv common/deploy/lambda-layers.zip common/deploy-ci/
            node common/scripts/install-run-rush.js deploy --overwrite --project @cats-cradle/api-gateway --create-archive api-gateway.zip
            mv common/deploy/api-gateway.zip common/deploy-ci/
            node common/scripts/install-run-rush.js deploy --overwrite --project @cats-cradle/character-sheet --create-archive character-sheet.zip
            mv common/deploy/character-sheet.zip common/deploy-ci/
            node common/scripts/install-run-rush.js deploy --overwrite --project @cats-cradle/luck-by-dice --create-archive luck-by-dice.zip
            mv common/deploy/luck-by-dice.zip common/deploy-ci/
            node common/scripts/install-run-rush.js deploy --overwrite --project @cats-cradle/email-service --create-archive email-service.zip
            mv common/deploy/email-service.zip common/deploy-ci/

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'common/deploy-ci'
          destination_dir: ''
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: https://aws-bucket.s3.ap-northeast-2.amazonaws.com/${{steps.S3.outputs.object_key}}/index.html
          state: 'success'
          deployment_id: ${{ steps.step-deployment-action.outputs.deployment_id }}