name: Test Coverage

on:
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        required: true
      IMPACTED_BY_SHA:
        required: true

jobs:
  rush-coverage:
    name: rush test:cov
    timeout-minutes: 25
    runs-on: ubuntu-latest
    steps:
      # pipeline get changed projects requires deep clone
      - name: Check out code base
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.0'

      - name: Cache rush
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: common/temp
          key: ${{ runner.os }}-build-branch-${{ hashFiles('common/config/rush/repo-state.json') }}
          restore-keys: |
            ${{ runner.os }}-build-pr-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install PNPM
        run: npm install --global pnpm@8.6.6

      - name: rush install
        run: node common/scripts/install-run-rush.js install -p

      - name: rush build
        run: node common/scripts/install-run-rush.js build

      - name: rush test:cov platform-package
        uses: neofinancial/mongo-memory-server-action@v1.0.2
        with:
          db-connection-env-var: MONGO_DATABASE_URI
          run-command: node common/scripts/install-run-rush.js test:cov --to tag:platform-package
          binary-version: 4.2.8
          instance-port: 27017
          instance-storageEngine: "ephemeralForTest"

      - name: rush test:cov library-package
        uses: neofinancial/mongo-memory-server-action@v1.0.2
        with:
          db-connection-env-var: MONGO_DATABASE_URI
          run-command: node common/scripts/install-run-rush.js test:cov --to tag:library-package
          binary-version: 4.2.8
          instance-port: 27017
          instance-storageEngine: "ephemeralForTest"

      - name: rush test:cov service-package mongo old
        uses: neofinancial/mongo-memory-server-action@v1.0.2
        with:
          db-connection-env-var: MONGO_DATABASE_URI
          run-command: node common/scripts/install-run-rush.js test:cov --to tag:mongo-old
          binary-version: 4.2.8
          instance-port: 27017
          instance-storageEngine: "ephemeralForTest"

      - name: rush test:cov service-package mongo-new
        run: node common/scripts/install-run-rush.js test:cov --to tag:mongo-new

      - name: Merge coverage reports
        run: npx @cats-cradle/rush-coverage@1.2.0

      - name: Submit merged coverage report
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
