name: Test

on:
  workflow_call:
    secrets:
      IMPACTED_BY_SHA:
        required: true

jobs:
  rush-test:
    name: rush test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code base
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check out code base
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ secrets.IMPACTED_BY_SHA }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'

      - name: Cache rush
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: common/temp
          key: ${{ runner.os }}-build-branch-${{ hashFiles('common/config/rush/repo-state.json') }}
          restore-keys: |
            ${{ runner.os }}-build-pr-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install PNPM
        run: npm install --global pnpm@8.6.2

      - name: Rush install
        run: node common/scripts/install-run-rush.js install -p

      - name: rush build
        run: node common/scripts/install-run-rush.js build

      - name: Test
        run: node common/scripts/install-run-rush.js test --impacted-by git:${{ secrets.IMPACTED_BY_SHA }}
