name: Deploy

on:
  workflow_call:
    secrets:
      AWS_DEPLOY_ACCESS_KEY_ID:
        required: true
      AWS_DEPLOY_SECRET_ACCESS_KEY:
        required: true
      AWS_DEPLOY_REGION:
        required: true

jobs:
  rush-deploy:
    name: rush deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'

      - name: cache rush
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: common/temp
          key: ${{ runner.os }}-build-branch-${{ hashFiles('common/config/rush/repo-state.json') }}
          restore-keys: |
            ${{ runner.os }}-build-pr-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup git
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com

      - name: rush install
        run: node common/scripts/install-run-rush.js install

      - name: rush build
        run: node common/scripts/install-run-rush.js build

      # build deployment package
      # https://rushjs.io/pages/maintainer/deploying/
      - name: rush deploy
        run: |
          rushListJson=$(node common/scripts/install-run-rush.js rush list --only tag:deploy-app --json | jq '.[]')
          projects=${rushListJson[projects]}
          for row in $(echo "${projects}" | jq -r '.[] | @base64'); do
            _jq() {
              echo "${row}" | base64 --decode | jq -r "${1}"
            }

            name=$(_jq '.name')
            appShortName=${name//@cats-cradle\//deploy_}

            echo "Rush deploy $name...."
            node node common/scripts/install-run-rush.js deploy --overwrite --project $name

            echo "Compressing $appShortName"
            tar -czvf $appShortName.tar.gz common/deploy --remove-files
          done

      # authenticate
      # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_DEPLOY_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_DEPLOY_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_DEPLOY_REGION }}
      #     role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      #     role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
      #     role-duration-seconds: 1200
      #     role-session-name: MySessionName

      # ship deployments for each project for use in aws code pipelines