name: Test Coverage

on:
  workflow_call:
    secrets:
      CODACY_PROJECT_TOKEN:
        required: true
      IMPACTED_BY_SHA:
        required: true
jobs:
  test-cov:
    name: test:cov
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: check out code base
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: check out code base
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ secrets.IMPACTED_BY_SHA }}

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '8.13.1'

      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'
          cache: 'pnpm'

      - name: cache nx
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: common/temp
          key: ${{ runner.os }}-build-branch-${{ hashFiles('.nx/lockfile.hash') }}
          restore-keys: |
            ${{ runner.os }}-build-pr-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: pnpm install
        # if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: projects build
        run: pnpm nx run-many -t build --all

      - name: test:cov scope:platform
        uses: neofinancial/mongo-memory-server-action@v1.0.2
        with:
          db-connection-env-var: MONGO_DATABASE_URI
          run-command: pnpm nx run-many -t test:cov --projects=tag:scope:platform
          binary-version: 4.2.8
          instance-port: 27017
          instance-storageEngine: "ephemeralForTest"

      - name: test:cov scope:libraries
        uses: neofinancial/mongo-memory-server-action@v1.0.2
        with:
          db-connection-env-var: MONGO_DATABASE_URI
          run-command: pnpm nx run-many -t test:cov --projects=tag:scope:libraries
          binary-version: 4.2.8
          instance-port: 27017
          instance-storageEngine: "ephemeralForTest"

      - name: test:cov scope:services
        uses: neofinancial/mongo-memory-server-action@v1.0.2
        with:
          db-connection-env-var: MONGO_DATABASE_URI
          run-command: pnpm nx run-many -t test:cov --projects=tag:cimongo
          binary-version: 4.2.8
          instance-port: 27017
          instance-storageEngine: "ephemeralForTest"

      - name: test:cov scope:services
        uses: neofinancial/mongo-memory-server-action@v1.0.2
        with:
          db-connection-env-var: MONGO_DATABASE_URI
          run-command: pnpm nx run-many -t test:cov --projects=tag:mongoshelf
          binary-version: 4.2.8
          instance-port: 27017
          instance-storageEngine: "ephemeralForTest"

      - name: test:cov scope:clients
        uses: neofinancial/mongo-memory-server-action@v1.0.2
        with:
          db-connection-env-var: MONGO_DATABASE_URI
          run-command: pnpm nx run-many -t test:cov --projects=tag:scope:clients
          binary-version: 4.2.8
          instance-port: 27017
          instance-storageEngine: "ephemeralForTest"

      - name: Merge coverage reports
        run: pnpm nx run coverage-fusion:start

      - name: Submit merged coverage report
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
