# libray and platform dependencies MUST be published to npm
# prior to services being deployed to S3 dependencies to ensure dependencies are avaliable

name: Deploy Artifacts

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_BUCKET:
        required: true
      AWS_REGION:
        required: true

jobs:
  rush-deploy:
    name: rush deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: step-deployment-action
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          description: 'Upload AWS S3'
          environment: AWS CodePipeline

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.0'

      - name: cache rush
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: common/temp
          key: ${{ runner.os }}-build-branch-${{ hashFiles('common/config/rush/repo-state.json') }}
          restore-keys: |
            ${{ runner.os }}-build-pr-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup git
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com

      - name: install pnpm needed for cdk NodeJsFunction esbuild
        run: npm install --global pnpm@8.6.6

      - name: rush install
        run: node common/scripts/install-run-rush.js install -p

      - name: rush build
        run: node common/scripts/install-run-rush.js build

      # publish dependencies prior to deploying to ensure that latest are avaliable
      # uses shouldPublish in rush.json
      # https://rushjs.io/pages/maintainer/publishing/

      - name: bump version
        run: node common/scripts/install-run-rush.js version --bump

      - name: rush publish to npmjs.org
        run: node common/scripts/install-run-rush.js publish --apply --publish --include-all --target-branch main --npm-auth-token ${NPM_TOKEN} --add-commit-details --set-access-level public
        env:
          NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # deploy project for pipeline
      - name: rush artifact
        run: node common/scripts/install-run-rush.js artifact

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'common/temp/dist'
          destination_dir: ''
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_url: https://aws-bucket.s3.ap-northeast-2.amazonaws.com/${{steps.S3.outputs.object_key}}/index.html
          state: 'success'
          deployment_id: ${{ steps.step-deployment-action.outputs.deployment_id }}