name: Close Stale

on:
  workflow_call:

jobs:
  stale:
    name: 'Close month old issues and PRs'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          start-date: '2023-01-01T00:00:00Z'
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          stale-pr-message: 'This PR is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 30 days with no activity. Please open a new issue if the issue is still relevant, linking to this one.'
          close-pr-message: 'This PR was closed because it has been stalled for 30 days with no activity. Please open a new PR if the issue is still relevant, linking to this one.'
          days-before-issue-stale: 30
          days-before-pr-stale: 90
          days-before-issue-close: 30
          days-before-pr-close: 30
          exempt-all-milestones: true
          exempt-issue-labels: Pinned
          exempt-pr-labels: Pinned
          exempt-draft-pr: true
          operations-per-run: 100
