name: CDK Synth

on:
  workflow_call:
    secrets:
      IMPACTED_BY_SHA:
        required: true

jobs:
  cdk-synth:
    name: cdk synth
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code base
        if: github.event_name == 'push'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check out code base
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ secrets.IMPACTED_BY_SHA }}

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'

      - name: cache rush
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: common/temp
          key: ${{ runner.os }}-build-branch-${{ hashFiles('common/config/rush/repo-state.json') }}
          restore-keys: |
            ${{ runner.os }}-build-pr-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: install pnpm needed for cdk NodeJsFunction esbuild
        run: npm install --global pnpm@8.6.2

      - name: rush install
        # if: steps.cache.outputs.cache-hit != 'true'
        run: node common/scripts/install-run-rush.js install

      - name: rush build
        run: node common/scripts/install-run-rush.js build
        env:
          PROJECT_ROOT: ${{ github.workspace }}

      - name: install cdk
        run: npm install --global aws-cdk@2.63.1
        env:
          PROJECT_ROOT: ${{ github.workspace }}

      - name: rush synth
        run: node common/scripts/install-run-rush.js cdk:synth --impacted-by git:${{ secrets.IMPACTED_BY_SHA }}
        env:
          PROJECT_ROOT: ${{ github.workspace }}
