name: Test

on:
    workflow_call:

jobs:
  rush-test:
    name: rush test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        run: git fetch origin "+refs/heads/main:refs/remotes/origin/main"

      - name: Fetch main branch from origin
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.18.0'

      - name: Cache rush
        id: cache
        uses: actions/cache@v3.2.2
        with:
          path: common/temp
          key: ${{ runner.os }}-build-branch-${{ hashFiles('common/config/rush/repo-state.json') }}
          restore-keys: |
            ${{ runner.os }}-build-pr-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Rush install
        # if: steps.cache.outputs.cache-hit != 'true'
        run: node common/scripts/install-run-rush.js install

      - name: Test
        run: node common/scripts/install-run-rush.js test
