name: ci

on:
  push:
    branches:
      - "main"

jobs:
  # https://docs.docker.com/build/ci/github-actions/examples/#cache
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          target: test
          push: true
          tags: hxtree/keepers-cradle:latest
          cache-from: type=registry,ref=hxtree/keepers-cradle:latest
          cache-to: type=inline

      - name: Download packages
        run: docker-compose run keepers-cradle rush update

      - name: Run unit tests
        run: docker compose run keepers-cradle rush test