name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
      uses: ./.github/workflows/reusable/build.yml
  coverage:
      uses: ./.github/workflows/reusable/coverage.yml
  lint:
      uses: ./.github/workflows/reusable/lint.yml
  test:
      uses: ./.github/workflows/reusable/test.yml

  # slack-notification:
  #   name: "Slack Notification"
  #   runs-on: ubuntu-latest
  #   if: always()
  #   needs:
  #     - docker-hub
  #   steps:
  #     - name: Send message to Slack API
  #       uses: archive/github-actions-slack@v2.0.0
  #       with:
  #         slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
  #         slack-channel: ${{ secrets.SLACK_CHANNEL_ID }}
  #         slack-text: |
  #           Event "${{ github.event_name }}" in "${{ github.repository }}" by @${{ github.actor }}
  #           Commit ${{ github.sha }}
  #           ${{ needs.composer-validate.result == 'success' && ':white_check_mark:' || ':no_entry_sign:' }} Composer Validate.
