name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-workflow-build:
    uses: ./.github/workflows/build.yml

  call-workflow-lint:
    uses: ./.github/workflows/lint.yml

  call-workflow-test:
    uses: ./.github/workflows/test.yml

  call-workflow-coverage:
    uses: ./.github/workflows/coverage.yml

  # slack-notification:
  #   name: "Slack Notification"
  #   runs-on: ubuntu-latest
  #   if: always()
  #   needs:
  #     - docker-hub
  #   steps:
  #     - name: Send message to Slack API
  #       uses: archive/github-actions-slack@v2.0.0
  #       with:
  #         slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
  #         slack-channel: ${{ secrets.SLACK_CHANNEL_ID }}
  #         slack-text: |
  #           Event "${{ github.event_name }}" in "${{ github.repository }}" by @${{ github.actor }}
  #           Commit ${{ github.sha }}
  #           ${{ needs.composer-validate.result == 'success' && ':white_check_mark:' || ':no_entry_sign:' }} Composer Validate.
