name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://github.com
    steps:
      - name: configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # this deployment would be for intergration testing purposes really
      # as to ensure code is deployable prior to merging to main.
      # as to ensure cdk changes build cloud formation templates that can successfully be deployed
      # todo consider monorepo rush build
      # need to be able to execute multiple code pipelines but only get one feed back
      # also this prevents a problem with avaliable of build environment
      # taskCat, CF template matching, might be better alternatives...

      # - name: Start CodePipeline
      #   uses: moia-oss/aws-codepipeline-trigger@v1
      #   with:
      #     pipeline: my-pipeline-int
      #     wait: true
      #     follow-codebuild: true
      # # TODO CodePipeline
      # https://github.com/aws-actions