name: Labeled

on:
  pull_request:
    types:
      - labeled

jobs:
  Deploy:
    if: |
      github.event.label.name == 'sandbox'
    uses: ./.github/workflows/call-deploy.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}