name: CI

on:
  push:
    branches: [ main ]

jobs:
  Lint:
    uses: ./.github/workflows/call-lint.yml
    secrets:
      IMPACTED_BY_SHA: ${{ github.event.before }}

  Build:
    uses: ./.github/workflows/call-build.yml
    secrets:
      IMPACTED_BY_SHA: ${{ github.event.before }}

  Test:
    uses: ./.github/workflows/call-test.yml
    secrets:
      IMPACTED_BY_SHA: ${{ github.event.before }}

  IaC:
    uses: ./.github/workflows/call-cdk-synth.yml
    secrets:
      IMPACTED_BY_SHA: ${{ github.event.before }}

  Coverage:
    uses: ./.github/workflows/call-coverage.yml
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      IMPACTED_BY_SHA: ${{ github.event.before }}

  Deploy:
    uses: ./.github/workflows/call-deploy.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  # slack-notification:
  #   name: "Slack Notification"
  #   runs-on: ubuntu-latest
  #   if: always()
  #   needs:
  #     - docker-hub
  #   steps:
  #     - name: Send message to Slack API
  #       uses: archive/github-actions-slack@v2.0.0
  #       with:
  #         slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
  #         slack-channel: ${{ secrets.SLACK_CHANNEL_ID }}
  #         slack-text: |
  #           Event "${{ github.event_name }}" in "${{ github.repository }}" by @${{ github.actor }}
  #           Commit ${{ github.sha }}
  #           ${{ needs.composer-validate.result == 'success' && ':white_check_mark:' || ':no_entry_sign:' }} Composer Validate.
