name: PR

on:
  pull_request

jobs:
  "Code Standards":
    uses: ./.github/workflows/call-lint.yml

  "Build":
    uses: ./.github/workflows/call-build.yml

  "Unit Test":
    uses: ./.github/workflows/call-test.yml

  "IaC Synthesis":
    uses: ./.github/workflows/call-cdk-synth.yml

  "Code Coverage":
    uses: ./.github/workflows/call-coverage.yml
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}