name: PR

on:
  pull_request

jobs:
  Build:
    uses: ./.github/workflows/call-build.yml

  Lint:
    uses: ./.github/workflows/call-lint.yml

  Test:
    uses: ./.github/workflows/call-test.yml

  IaC:
    uses: ./.github/workflows/call-cdk-synth.yml
    secrets:
      PROJECT_ROOT: ${{ github.workspace }}

  Coverage:
    uses: ./.github/workflows/call-coverage.yml
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}