name: PR

on:
  pull_request

jobs:
  Lint:
    uses: ./.github/workflows/call-lint.yml

  Build:
    uses: ./.github/workflows/call-build.yml

  Test:
    uses: ./.github/workflows/call-test.yml
    secrets:
      IMPACTED_BY_SHA: ${{ github.event.pull_request.head.sha }}

  IaC:
    uses: ./.github/workflows/call-cdk-synth.yml

  Coverage:
    uses: ./.github/workflows/call-coverage.yml
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}