name: PR

on:
  pull_request

jobs:
  Lint:
    uses: ./.github/workflows/call-lint.yml
    secrets:
      IMPACTED_BY_SHA: ${{ github.event.pull_request.head.sha }}

  Build:
    uses: ./.github/workflows/call-build.yml
    secrets:
      IMPACTED_BY_SHA: ${{ github.event.pull_request.head.sha }}

  Test:
    uses: ./.github/workflows/call-test.yml
    secrets:
      IMPACTED_BY_SHA: ${{ github.event.pull_request.head.sha }}

  IaC:
    uses: ./.github/workflows/call-cdk-synth.yml
    secrets:
      IMPACTED_BY_SHA: ${{ github.event.pull_request.head.sha }}

  Coverage:
    uses: ./.github/workflows/call-coverage.yml
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      IMPACTED_BY_SHA: ${{ github.event.pull_request.head.sha }}

  # Deploy:
  #   uses: ./.github/workflows/call-deploy.yml
  #   secrets:
  #     AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
  #     AWS_REGION: ${{ secrets.AWS_REGION }}
