name: Unit Test

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3

      - name: Install rush
        run: node common/scripts/install-run-rush.js install
      - run: rush install --no-link

      - name: Unit tests
        run: rush test